name: Deploy API to Vercel

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Create Vercel configuration
        run: |
          echo '{
            "version": 2,
            "builds": [{
              "src": "app.js",
              "use": "@vercel/node-server"
            }],
            "routes": [{
              "src": "/api/feed(.*)",
              "dest": "app.js"
            }]
          }' > vercel.json

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v1
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git_root_path: '/'
          team: 'hua123an'